version: '3.7'
services:
    postgres:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: "Admin"
            PGDATA: /var/lib/postgres/data/PGDATA
        ports:
            - 15432:5432
        volumes: 
            - pgdata:/var/lib/postgres/data
        networks: 
            postgres_network:
                aliases: 
                    - postgres_host
volumes: 
    pgdata: {}
networks: 
    postgres_network:
        name: postgres_net
        driver: bridge